version: 0.0
os: linux
files:
 - source: /
   destination: /home/ubuntu/NewsEmotionsExtraction
permissions:
  - object: /home/ubuntu/NewsEmotionsExtraction
    mode: 755
    pattern: "**"
    owner: ubuntu
    group: ubuntu
hooks:
  AfterInstall:
   - location: installing_dependencies.sh
     timeout: 300
     runas: root
   - location: start_server.sh
     timeout: 300
     runas: root